global using System.Text.Json;
global using CloudAccounting.Core.Models;
global using CloudAccounting.Core.Repositories;
global using CloudAccounting.Infrastructure.Data;
// global using CloudAccounting.Infrastructure.Data.Models;
global using CloudAccounting.Infrastructure.Data.Interfaces;
global using CloudAccounting.Infrastructure.Data.Repositories;
global using CloudAccounting.IntegrationTestsWebApi.TestData;
global using CloudAccounting.SharedKernel.Utilities;
global using Mapster;
global using MapsterMapper;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Caching.Memory;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Logging.Abstractions;
using FluentValidation;
