// <auto-generated />
using System;
using CloudAccounting.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudAccounting.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CloudAccountingContext))]
    [Migration("20260219151432_Index-Company-Voucher")]
    partial class IndexCompanyVoucher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.BankOpeningStatementDM", b =>
                {
                    b.Property<int>("SrNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("SR_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SrNo"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<decimal>("Credit")
                        .HasColumnType("MONEY")
                        .HasColumnName("VCHCR");

                    b.Property<decimal>("Debit")
                        .HasColumnType("MONEY")
                        .HasColumnName("VCHDR");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("BIT")
                        .HasColumnName("RECONCILED");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REMARKS");

                    b.HasKey("SrNo")
                        .HasName("PK_BANKS_OS");

                    b.HasIndex("CompanyCode", "AccountCode");

                    b.ToTable("GL_BANKS_OS", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.BudgetDM", b =>
                {
                    b.Property<string>("AccountClassification")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COANATURE");

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<decimal?>("BudgetAmount1")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT1");

                    b.Property<decimal?>("BudgetAmount10")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT10");

                    b.Property<decimal?>("BudgetAmount11")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT11");

                    b.Property<decimal?>("BudgetAmount12")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT12");

                    b.Property<decimal?>("BudgetAmount2")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT2");

                    b.Property<decimal?>("BudgetAmount3")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT3");

                    b.Property<decimal?>("BudgetAmount4")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT4");

                    b.Property<decimal?>("BudgetAmount5")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT5");

                    b.Property<decimal?>("BudgetAmount6")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT6");

                    b.Property<decimal?>("BudgetAmount7")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT7");

                    b.Property<decimal?>("BudgetAmount8")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT8");

                    b.Property<decimal?>("BudgetAmount9")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET_AMOUNT9");

                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<short?>("CompanyYear")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("COYEAR");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CCCODE");

                    b.Property<bool?>("Criterion")
                        .HasColumnType("BIT")
                        .HasColumnName("CRITERION");

                    b.HasIndex("CompanyCode", "AccountCode");

                    b.ToTable("GL_BUDGET", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.BudgetReportDM", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<string>("AccountFrom")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ACCOUNTFROM");

                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COATITLE");

                    b.Property<string>("AccountTo")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ACCOUNTTO");

                    b.Property<decimal?>("Actual")
                        .HasColumnType("MONEY")
                        .HasColumnName("ACTUAL");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("MONEY")
                        .HasColumnName("BUDGET");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONAME");

                    b.Property<bool?>("GrandTotal")
                        .HasColumnType("BIT")
                        .HasColumnName("GRAND_TOTAL");

                    b.Property<string>("MonthFrom")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("MONTHFROM");

                    b.Property<string>("MonthTo")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("MONTHTO");

                    b.Property<decimal?>("Percent")
                        .HasColumnType("DECIMAL(7,2)")
                        .HasColumnName("PERCENT");

                    b.Property<DateTime?>("PrintedOn")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("PRINTEDON");

                    b.Property<string>("Status")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("STATUS");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.Property<decimal?>("Variance")
                        .HasColumnType("MONEY")
                        .HasColumnName("VARIANCE");

                    b.ToTable("GL_BUDGET_REPORT", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", b =>
                {
                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<string>("AccountCode")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<string>("AccountClassification")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COANATURE");

                    b.Property<byte?>("AccountLevel")
                        .HasColumnType("TINYINT")
                        .HasColumnName("COALEVEL");

                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COATITLE");

                    b.Property<string>("AccountType")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COATYPE");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CCCODE");

                    b.HasKey("CompanyCode", "AccountCode")
                        .HasName("GL_COA_PK");

                    b.ToTable("GL_COA", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.CompanyDM", b =>
                {
                    b.Property<int>("CompanyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CompanyCode"));

                    b.Property<string>("Address")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("COADDRESS");

                    b.Property<string>("City")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COCITY");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONAME");

                    b.Property<string>("Currency")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COCURRENCY");

                    b.Property<string>("Fax")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COFAX");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COPHONE");

                    b.Property<string>("Zipcode")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("COZIP");

                    b.HasKey("CompanyCode")
                        .HasName("GL_COMPANY_PK");

                    b.HasIndex("CompanyName")
                        .IsUnique()
                        .HasFilter("[CONAME] IS NOT NULL");

                    b.ToTable("GL_COMPANY", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyCode = 1,
                            Address = "123 Main Street",
                            City = "Dallas",
                            CompanyName = "BTechnical Consulting",
                            Currency = "USD",
                            Fax = "214-555-5678",
                            Phone = "214-555-1234",
                            Zipcode = "75201"
                        },
                        new
                        {
                            CompanyCode = 2,
                            Address = "456 Elm Street",
                            City = "Seattle",
                            CompanyName = "Contoso Ltd.",
                            Currency = "USD",
                            Fax = "206-555-5432",
                            Phone = "206-555-9876",
                            Zipcode = "98101"
                        },
                        new
                        {
                            CompanyCode = 3,
                            Address = "789 Oak Avenue",
                            City = "Chicago",
                            CompanyName = "Fabrikam Inc.",
                            Currency = "USD",
                            Fax = "312-555-1357",
                            Phone = "312-555-2468",
                            Zipcode = "60601"
                        },
                        new
                        {
                            CompanyCode = 4,
                            Address = "321 Pine Road",
                            City = "Denver",
                            CompanyName = "Adventure Works",
                            Currency = "USD",
                            Fax = "303-555-4321",
                            Phone = "303-555-7890",
                            Zipcode = "80201"
                        },
                        new
                        {
                            CompanyCode = 5,
                            Address = "654 Maple Lane",
                            City = "Boston",
                            CompanyName = "Contoso Pharmaceuticals",
                            Currency = "USD",
                            Fax = "617-555-1357",
                            Phone = "617-555-2468",
                            Zipcode = "02101"
                        });
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.CostCenterDM", b =>
                {
                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CCCODE");

                    b.Property<byte?>("CostCenterLevel")
                        .HasColumnType("TINYINT")
                        .HasColumnName("CCLEVEL");

                    b.Property<string>("CostCenterTitle")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("CCTITLE");

                    b.HasKey("CompanyCode", "CostCenterCode")
                        .HasName("GL_COST_CENTER_PK");

                    b.ToTable("GL_COST_CENTER", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.DashboardDM", b =>
                {
                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ACCOUNTTITLE");

                    b.Property<decimal?>("CurrentYear")
                        .HasColumnType("MONEY")
                        .HasColumnName("CURRENTYEAR");

                    b.Property<decimal?>("Current_Year")
                        .HasColumnType("MONEY")
                        .HasColumnName("CURRENT_YEAR");

                    b.Property<decimal?>("Previous_Year")
                        .HasColumnType("MONEY")
                        .HasColumnName("PREVIOUS_YEAR");

                    b.Property<decimal?>("Previousyear")
                        .HasColumnType("MONEY")
                        .HasColumnName("PREVIOUSYEAR");

                    b.Property<string>("RatioTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("RATIOTITLE");

                    b.Property<int?>("Srno")
                        .HasColumnType("INT")
                        .HasColumnName("SRNO");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.ToTable("GL_DASHBOARD", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FeedbackDM", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("FEEDBACKID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("CustomerEmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("CUSTEMAIL");

                    b.Property<string>("CustomerFeedback")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("CUSTFEEDBACK");

                    b.Property<string>("CustomerName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CUSTNAME");

                    b.Property<DateTime?>("Timestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasColumnName("TS")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("FeedbackId")
                        .HasName("GL_FEEDBACK_PK");

                    b.ToTable("GL_FEEDBACK", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FinancialStatementReportDM", b =>
                {
                    b.Property<bool?>("Calculation")
                        .HasColumnType("BIT")
                        .HasColumnName("CALCULATION");

                    b.Property<string>("CompanyMonthName")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("COMONTHNAME");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONAME");

                    b.Property<short?>("CompanyYear")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("COYEAR");

                    b.Property<decimal?>("CurrentBalance")
                        .HasColumnType("MONEY")
                        .HasColumnName("CURRENTBALANCE");

                    b.Property<string>("FinancialStatementAccount")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FSACCOUNT");

                    b.Property<bool?>("Heading")
                        .HasColumnType("BIT")
                        .HasColumnName("HEADING");

                    b.Property<bool?>("NetValue")
                        .HasColumnType("BIT")
                        .HasColumnName("NETVALUE");

                    b.Property<bool?>("Notes")
                        .HasColumnType("BIT")
                        .HasColumnName("NOTES");

                    b.Property<string>("NotesCode")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("NOTESCODE");

                    b.Property<string>("NotesTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("NOTESTITLE");

                    b.Property<decimal?>("Percent")
                        .HasColumnType("DECIMAL(7,2)")
                        .HasColumnName("PERCENT");

                    b.Property<decimal?>("PreviousBalance")
                        .HasColumnType("MONEY")
                        .HasColumnName("PREVIOUSBALANCE");

                    b.Property<string>("ReportCode")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("REPORTCODE");

                    b.Property<string>("ReportTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REPORTTITLE");

                    b.Property<int?>("Srno")
                        .HasColumnType("INT")
                        .HasColumnName("SRNO");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.ToTable("GL_FS_REPORT", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FinancialStatementSetupDM", b =>
                {
                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<string>("ReportCode")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("REPORTCODE");

                    b.Property<string>("FinancialStatementAccount")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("FSACCOUNT");

                    b.Property<string>("AccountFrom")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ACCOUNTFROM");

                    b.Property<string>("AccountTo")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("ACCOUNTTO");

                    b.Property<string>("ReportTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("REPORTTITLE");

                    b.HasKey("CompanyCode", "ReportCode", "FinancialStatementAccount")
                        .HasName("GL_FS_SETUP_PK");

                    b.ToTable("GL_FS_SETUP", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FiscalYearDM", b =>
                {
                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<short>("CompanyYear")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("COYEAR");

                    b.Property<byte>("CompanyMonthId")
                        .HasColumnType("TINYINT")
                        .HasColumnName("COMONTHID");

                    b.Property<string>("CompanyMonthName")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)")
                        .HasColumnName("COMONTHNAME");

                    b.Property<bool?>("InitialYear")
                        .HasColumnType("BIT")
                        .HasColumnName("INITIAL_YEAR");

                    b.Property<bool?>("MonthClosed")
                        .HasColumnType("BIT")
                        .HasColumnName("MONTH_CLOSED");

                    b.Property<DateTime?>("PeriodFrom")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("PFROM");

                    b.Property<DateTime?>("PeriodTo")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("PTO");

                    b.Property<DateTime?>("TyeExecuted")
                        .HasColumnType("DATE")
                        .HasColumnName("TYE_EXECUTED");

                    b.Property<bool?>("YearClosed")
                        .HasColumnType("BIT")
                        .HasColumnName("YEAR_CLOSED");

                    b.HasKey("CompanyCode", "CompanyYear", "CompanyMonthId")
                        .HasName("GL_FISCAL_YEAR_PK");

                    b.ToTable("GL_FISCAL_YEAR", (string)null);

                    b.HasData(
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)1,
                            CompanyMonthName = "January",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)2,
                            CompanyMonthName = "February",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)3,
                            CompanyMonthName = "March",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)4,
                            CompanyMonthName = "April",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)5,
                            CompanyMonthName = "May",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)6,
                            CompanyMonthName = "June",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)7,
                            CompanyMonthName = "July",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)8,
                            CompanyMonthName = "August",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)9,
                            CompanyMonthName = "September",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)10,
                            CompanyMonthName = "October",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)11,
                            CompanyMonthName = "November",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2024,
                            CompanyMonthId = (byte)12,
                            CompanyMonthName = "December",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)1,
                            CompanyMonthName = "January",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)2,
                            CompanyMonthName = "February",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)3,
                            CompanyMonthName = "March",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)4,
                            CompanyMonthName = "April",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)5,
                            CompanyMonthName = "May",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)6,
                            CompanyMonthName = "June",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)7,
                            CompanyMonthName = "July",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 7, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)8,
                            CompanyMonthName = "August",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)9,
                            CompanyMonthName = "September",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)10,
                            CompanyMonthName = "October",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)11,
                            CompanyMonthName = "November",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        },
                        new
                        {
                            CompanyCode = 1,
                            CompanyYear = (short)2025,
                            CompanyMonthId = (byte)12,
                            CompanyMonthName = "December",
                            InitialYear = true,
                            MonthClosed = false,
                            PeriodFrom = new DateTime(2025, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PeriodTo = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearClosed = false
                        });
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.GroupsDetailDM", b =>
                {
                    b.Property<string>("AllowAccess")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ALLOW_ACCESS");

                    b.Property<short?>("GroupId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("GROUPID");

                    b.Property<string>("ItemRole")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ITEMROLE");

                    b.Property<short?>("PageId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("PAGEID");

                    b.Property<short?>("SegmentId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("SEGMENTID");

                    b.Property<short?>("SegmentParent")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("SEGMENTPARENT");

                    b.Property<string>("SegmentType")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("SEGMENTTYPE");

                    b.HasIndex("GroupId");

                    b.HasIndex("SegmentId");

                    b.ToTable("GL_GROUPS_DETAIL", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.GroupsMasterDM", b =>
                {
                    b.Property<short>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasColumnName("GROUPID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("GroupId"));

                    b.Property<string>("GroupTitle")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("GROUPTITLE");

                    b.HasKey("GroupId")
                        .HasName("GL_GROUPS_PK");

                    b.ToTable("GL_GROUPS_MASTER", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.ReconcileReportDM", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COATITLE");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("MONEY")
                        .HasColumnName("AMOUNT");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONAME");

                    b.Property<string>("Description")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("VCHDESCRIPTION");

                    b.Property<string>("MonthYear")
                        .HasMaxLength(14)
                        .IsUnicode(false)
                        .HasColumnType("varchar(14)")
                        .HasColumnName("MONTHYEAR");

                    b.Property<string>("Reference")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("VCHREFERENCE");

                    b.Property<DateTime?>("ReportDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("REPORTDATE");

                    b.Property<int?>("Srno")
                        .HasColumnType("INT")
                        .HasColumnName("SRNO");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.Property<DateTime?>("VoucherDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("VCHDATE");

                    b.Property<int?>("VoucherNumber")
                        .HasColumnType("INT")
                        .HasColumnName("VCHNO");

                    b.Property<string>("VoucherType")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("VCHTYPE");

                    b.ToTable("GL_RECONCILE_REPORT", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.SegmentDM", b =>
                {
                    b.Property<short>("SegmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("SMALLINT")
                        .HasColumnName("SEGMENTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("SegmentId"));

                    b.Property<string>("ItemRole")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("ITEMROLE");

                    b.Property<short?>("PageId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("PAGEID");

                    b.Property<short?>("SegmentParent")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("SEGMENTPARENT");

                    b.Property<string>("SegmentTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("SEGMENTTITLE");

                    b.Property<string>("SegmentType")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("SEGMENTTYPE");

                    b.HasKey("SegmentId")
                        .HasName("GL_SEGMENTS_PK");

                    b.ToTable("GL_SEGMENTS", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TransactionDetailDM", b =>
                {
                    b.Property<int>("LineNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("LINE_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LineNumber"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<int>("CompanyCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<string>("CostCenterCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CCCODE");

                    b.Property<decimal>("Credit")
                        .HasColumnType("MONEY")
                        .HasColumnName("VCHCR");

                    b.Property<decimal>("Debit")
                        .HasColumnType("MONEY")
                        .HasColumnName("VCHDR");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("VCHDESCRIPTION");

                    b.Property<bool>("Reconciled")
                        .HasColumnType("BIT")
                        .HasColumnName("RECONCILED");

                    b.Property<string>("Reference")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("VCHREFERENCE");

                    b.Property<int>("TransactionNumber")
                        .HasColumnType("INT")
                        .HasColumnName("TRAN_NO");

                    b.HasKey("LineNumber")
                        .HasName("PK_TRAN_DETAIL");

                    b.HasIndex("TransactionNumber");

                    b.HasIndex("CompanyCode", "AccountCode");

                    b.HasIndex("CompanyCode", "CostCenterCode");

                    b.ToTable("GL_TRAN_DETAIL", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TransactionMasterDM", b =>
                {
                    b.Property<int>("TransactionNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("TRAN_NO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionNumber"));

                    b.Property<bool>("Closing")
                        .HasColumnType("BIT")
                        .HasColumnName("CLOSING");

                    b.Property<int>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<byte>("CompanyMonth")
                        .HasColumnType("TINYINT")
                        .HasColumnName("COMONTHID");

                    b.Property<short>("CompanyYear")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("COYEAR");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("CREATEDBY");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("CREATEDON");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("VCHDESCRIPTION");

                    b.Property<string>("Posted")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("VCHPOSTED");

                    b.Property<string>("Verified")
                        .IsRequired()
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("VCHVERIFIED");

                    b.Property<int>("VoucherCode")
                        .HasColumnType("INT")
                        .HasColumnName("VCHCODE");

                    b.Property<DateTime>("VoucherDate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("VCHDATE");

                    b.Property<int>("VoucherNumber")
                        .HasColumnType("INT")
                        .HasColumnName("VCHNO");

                    b.HasKey("TransactionNumber")
                        .HasName("PK_TRAN_MASTER");

                    b.HasIndex("VoucherCode");

                    b.HasIndex("CompanyCode", "CompanyYear", "CompanyMonth");

                    b.ToTable("GL_TRAN_MASTER", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TrialBalanceDM", b =>
                {
                    b.Property<string>("AccountCode")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("COACODE");

                    b.Property<byte?>("AccountLevel")
                        .HasColumnType("TINYINT")
                        .HasColumnName("COALEVEL");

                    b.Property<string>("AccountTitle")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("COATITLE");

                    b.Property<decimal?>("ActivityCredit")
                        .HasColumnType("MONEY")
                        .HasColumnName("ACTIVITYCR");

                    b.Property<decimal?>("ActivityDebit")
                        .HasColumnType("MONEY")
                        .HasColumnName("ACTIVITYDR");

                    b.Property<decimal?>("ClosingCredit")
                        .HasColumnType("MONEY")
                        .HasColumnName("CLOSINGCR");

                    b.Property<decimal?>("ClosingDebit")
                        .HasColumnType("MONEY")
                        .HasColumnName("CLOSINGDR");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CONAME");

                    b.Property<string>("CostCenterCode")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("CCCODE");

                    b.Property<string>("CostCenterTitle")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)")
                        .HasColumnName("CCTITLE");

                    b.Property<string>("FromAccount")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("FROMACCOUNT");

                    b.Property<bool?>("GrandTotal")
                        .HasColumnType("BIT")
                        .HasColumnName("GRAND_TOTAL");

                    b.Property<decimal?>("OpeningCredit")
                        .HasColumnType("MONEY")
                        .HasColumnName("OPENCR");

                    b.Property<decimal?>("OpeningDebit")
                        .HasColumnType("MONEY")
                        .HasColumnName("OPENDR");

                    b.Property<byte?>("ReportLevel")
                        .HasColumnType("TINYINT")
                        .HasColumnName("REPORTLEVEL");

                    b.Property<DateTime?>("Tbdate")
                        .HasColumnType("DATETIME2")
                        .HasColumnName("TBDATE");

                    b.Property<string>("ToAccount")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)")
                        .HasColumnName("TOACCOUNT");

                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.ToTable("GL_TRIAL_BALANCE", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.UserDM", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("USERID");

                    b.Property<string>("Admin")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)")
                        .HasColumnName("ADMIN");

                    b.Property<int?>("CompanyCode")
                        .HasColumnType("INT")
                        .HasColumnName("COCODE");

                    b.Property<byte?>("CompanyMonthId")
                        .HasColumnType("TINYINT")
                        .HasColumnName("COMONTHID");

                    b.Property<short?>("CompanyYear")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("COYEAR");

                    b.Property<short?>("GroupId")
                        .HasColumnType("SMALLINT")
                        .HasColumnName("GROUPID");

                    b.Property<string>("Password")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)")
                        .HasColumnName("PASSWORD");

                    b.HasKey("UserId")
                        .HasName("GL_USERS_PK");

                    b.HasIndex("CompanyCode");

                    b.HasIndex("GroupId");

                    b.ToTable("GL_USERS", (string)null);
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.VoucherDM", b =>
                {
                    b.Property<int>("VoucherCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("VCHCODE");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoucherCode"));

                    b.Property<byte?>("VoucherClassification")
                        .HasColumnType("TINYINT")
                        .HasColumnName("VCHNATURE");

                    b.Property<string>("VoucherTitle")
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("VCHTITLE");

                    b.Property<string>("VoucherType")
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("varchar(6)")
                        .HasColumnName("VCHTYPE");

                    b.HasKey("VoucherCode")
                        .HasName("GL_VOUCHER_PK");

                    b.HasIndex("VoucherType")
                        .IsUnique()
                        .HasFilter("[VCHTYPE] IS NOT NULL");

                    b.ToTable("GL_VOUCHER", (string)null);

                    b.HasData(
                        new
                        {
                            VoucherCode = 1,
                            VoucherClassification = (byte)1,
                            VoucherTitle = "Bank Payment Voucher",
                            VoucherType = "BPV"
                        },
                        new
                        {
                            VoucherCode = 2,
                            VoucherClassification = (byte)3,
                            VoucherTitle = "Local Sales Invoice",
                            VoucherType = "LSI"
                        },
                        new
                        {
                            VoucherCode = 3,
                            VoucherClassification = (byte)2,
                            VoucherTitle = "Bank Receipt Voucher",
                            VoucherType = "BRV"
                        },
                        new
                        {
                            VoucherCode = 4,
                            VoucherClassification = (byte)3,
                            VoucherTitle = "Adjustment Voucher",
                            VoucherType = "ADJ"
                        },
                        new
                        {
                            VoucherCode = 5,
                            VoucherClassification = (byte)1,
                            VoucherTitle = "Purchase Order",
                            VoucherType = "PO"
                        });
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.BankOpeningStatementDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("BankOpeningStatements")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_BANKS_OS1");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", "COANavigation")
                        .WithMany("BankOpeningStatements")
                        .HasForeignKey("CompanyCode", "AccountCode")
                        .IsRequired()
                        .HasConstraintName("FK_BANKS_OS2");

                    b.Navigation("COANavigation");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.BudgetDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany()
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_BUDGET1");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", "COANavigation")
                        .WithMany()
                        .HasForeignKey("CompanyCode", "AccountCode")
                        .IsRequired()
                        .HasConstraintName("FK_BUDGET2");

                    b.Navigation("COANavigation");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("ChartOfAccounts")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_COA");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.CostCenterDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("CostCenters")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_COST_CENTER");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FiscalYearDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("FiscalYears")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_FISCAL_YEAR");

                    b.Navigation("CompanyCodeNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.GroupsDetailDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.GroupsMasterDM", "GroupsMasterNavigation")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_GROUP_DETAIL");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.SegmentDM", "SegmentNavigation")
                        .WithMany()
                        .HasForeignKey("SegmentId")
                        .HasConstraintName("FK_USER_GROUPS");

                    b.Navigation("GroupsMasterNavigation");

                    b.Navigation("SegmentNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TransactionDetailDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_DETAIL1");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.TransactionMasterDM", "TransactionMasterNavigation")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("TransactionNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_DETAIL2");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", "COANavigation")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("CompanyCode", "AccountCode")
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_DETAIL4");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CostCenterDM", "CostCenterNavigation")
                        .WithMany("TransactionDetails")
                        .HasForeignKey("CompanyCode", "CostCenterCode")
                        .HasConstraintName("FK_TRAN_DETAIL3");

                    b.Navigation("COANavigation");

                    b.Navigation("CompanyCodeNavigation");

                    b.Navigation("CostCenterNavigation");

                    b.Navigation("TransactionMasterNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TransactionMasterDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("CompanyCode")
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_MASTER1");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.VoucherDM", "VoucherNavigation")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("VoucherCode")
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_MASTER2");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.FiscalYearDM", "FiscalYearNavigation")
                        .WithMany("TransactionMasters")
                        .HasForeignKey("CompanyCode", "CompanyYear", "CompanyMonth")
                        .IsRequired()
                        .HasConstraintName("FK_TRAN_MASTER3");

                    b.Navigation("CompanyCodeNavigation");

                    b.Navigation("FiscalYearNavigation");

                    b.Navigation("VoucherNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.UserDM", b =>
                {
                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.CompanyDM", "CompanyCodeNavigation")
                        .WithMany("Users")
                        .HasForeignKey("CompanyCode")
                        .HasConstraintName("FK_USERS");

                    b.HasOne("CloudAccounting.Infrastructure.Data.Models.GroupsMasterDM", "GroupsMasterNavigation")
                        .WithMany("Users")
                        .HasForeignKey("GroupId")
                        .HasConstraintName("FK_USERS2");

                    b.Navigation("CompanyCodeNavigation");

                    b.Navigation("GroupsMasterNavigation");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.ChartOfAccountsDM", b =>
                {
                    b.Navigation("BankOpeningStatements");

                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.CompanyDM", b =>
                {
                    b.Navigation("BankOpeningStatements");

                    b.Navigation("ChartOfAccounts");

                    b.Navigation("CostCenters");

                    b.Navigation("FiscalYears");

                    b.Navigation("TransactionDetails");

                    b.Navigation("TransactionMasters");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.CostCenterDM", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.FiscalYearDM", b =>
                {
                    b.Navigation("TransactionMasters");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.GroupsMasterDM", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.TransactionMasterDM", b =>
                {
                    b.Navigation("TransactionDetails");
                });

            modelBuilder.Entity("CloudAccounting.Infrastructure.Data.Models.VoucherDM", b =>
                {
                    b.Navigation("TransactionMasters");
                });
#pragma warning restore 612, 618
        }
    }
}
